/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recepcionista;

import UI.Recepcionista.Paquetes.*;
import Models.Cliente;
import UI.Admin.CrudUsuarios.*;
import Models.Usuario;
import SQL.ManejoTabla;
import SQL.ObtenerDatos;
import SQL.RegistroCliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form crearUser
     */
    public static int PAQUETES_EN_DESTINO = 16;

    public Inicio() {
        initComponents();
        mostrarPaquetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquete = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Paquetes por entregar:");
        add(jLabel2);
        jLabel2.setBounds(750, 40, 220, 60);

        tablaPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPaquete);

        add(jScrollPane1);
        jScrollPane1.setBounds(380, 120, 930, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPaqueteMouseClicked

    }//GEN-LAST:event_tablaPaqueteMouseClicked

    private void mostrarPaquetes() {
        try {
            ManejoTabla.mostrarTablas(tablaPaquete, PAQUETES_EN_DESTINO, null);
        } catch (ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaquete;
    // End of variables declaration//GEN-END:variables
}
