/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recepcionista;

import UI.Admin.*;
import Ui.Admin.CrudUsuarios.DesactivarUsuario;
import Ui.Admin.CrudUsuarios.EditUser;
import Ui.Admin.CrudUsuarios.CrearUsuario;
import Ui.Admin.CrudRutas.CrearRuta;
import Ui.Admin.CrudRutas.CrearDestino;
import UI.Info;
import SQL.Conexion;
import UI.Admin.Tarifas.EditTarifaDestino;
import UI.Login;
import UI.Recepcionista.Paquetes.EditarCliente;
import UI.Recepcionista.Paquetes.EnviarPaquetes;
import Ui.Admin.Tarifas.Tarifas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Gamcas
 */
public class PrincipalRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form FormAdministrador
     */
    ImageIcon icono = new ImageIcon("src/Imagenes/user.png");
    Info info = new Info();
    public static int PANTALLA_ACTIVAR = 1;
    public static int PANTALLA_DESACTIVAR = 2;
    public static int PANTALLA_TARIFA_OPERACION = 1;
    public static int PANTALLA_TARIFA_LIBRA = 2;
    public static int PANTALLA_TARIFA_PRIORIDAD = 3;

    public PrincipalRecepcionista() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setTitle("Recepcionista");
        this.setExtendedState(MAXIMIZED_BOTH);
        JpInfo.removeAll();
        JpInfo.add(info, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        ContenedorPrincipal = new javax.swing.JPanel();
        JpMenu = new javax.swing.JPanel();
        iconUserInSesion = new javax.swing.JLabel();
        UserInSesion = new javax.swing.JLabel();
        separarUserInSesion = new javax.swing.JSeparator();
        iconCreateUser = new javax.swing.JLabel();
        iconEditUser = new javax.swing.JLabel();
        btnRecepcion = new javax.swing.JLabel();
        btnEntrega = new javax.swing.JLabel();
        separarUsuarios = new javax.swing.JSeparator();
        btnVerNoEntregados = new javax.swing.JLabel();
        iconNewRuta = new javax.swing.JLabel();
        btnLocalizar = new javax.swing.JLabel();
        separarRutas = new javax.swing.JSeparator();
        iconQuitPuntoControl = new javax.swing.JLabel();
        separarPuntosControl = new javax.swing.JSeparator();
        iconTarifaPrioridad = new javax.swing.JLabel();
        btnTarifaPrioridad = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        separarUsuarios1 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        JpContenedor = new javax.swing.JPanel();
        JpTitulo = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JpInfo = new javax.swing.JPanel();

        jLabel6.setText("fin");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ContenedorPrincipal.setLayout(new java.awt.BorderLayout());

        JpMenu.setBackground(new java.awt.Color(0, 102, 102));
        JpMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        JpMenu.setPreferredSize(new java.awt.Dimension(200, 712));
        JpMenu.setLayout(null);

        iconUserInSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        JpMenu.add(iconUserInSesion);
        iconUserInSesion.setBounds(30, 20, 40, 40);

        UserInSesion.setForeground(new java.awt.Color(255, 255, 255));
        UserInSesion.setText("Nombre Usuario");
        JpMenu.add(UserInSesion);
        UserInSesion.setBounds(70, 20, 110, 40);

        separarUserInSesion.setBackground(new java.awt.Color(0, 0, 0));
        separarUserInSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpMenu.add(separarUserInSesion);
        separarUserInSesion.setBounds(0, 0, 200, 80);

        iconCreateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recepcionPaquete.png"))); // NOI18N
        JpMenu.add(iconCreateUser);
        iconCreateUser.setBounds(10, 240, 40, 40);

        iconEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entregaPaquete.png"))); // NOI18N
        JpMenu.add(iconEditUser);
        iconEditUser.setBounds(10, 320, 40, 40);

        btnRecepcion.setForeground(new java.awt.Color(255, 255, 255));
        btnRecepcion.setText("Recepcion de Paquetes");
        btnRecepcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecepcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecepcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecepcionMouseExited(evt);
            }
        });
        JpMenu.add(btnRecepcion);
        btnRecepcion.setBounds(50, 240, 140, 40);

        btnEntrega.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrega.setText("Entrega de Paquetes");
        btnEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntregaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntregaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntregaMouseExited(evt);
            }
        });
        JpMenu.add(btnEntrega);
        btnEntrega.setBounds(50, 320, 140, 40);

        separarUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarUsuarios);
        separarUsuarios.setBounds(0, 220, 200, 20);

        btnVerNoEntregados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerNoEntregados.setText("<html>Ver paquetes no entregados");
        btnVerNoEntregados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerNoEntregadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerNoEntregadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerNoEntregadosMouseExited(evt);
            }
        });
        JpMenu.add(btnVerNoEntregados);
        btnVerNoEntregados.setBounds(50, 410, 140, 40);

        iconNewRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevaRuta.png"))); // NOI18N
        JpMenu.add(iconNewRuta);
        iconNewRuta.setBounds(10, 500, 40, 40);

        btnLocalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalizar.setText("Localizar Paquetes");
        btnLocalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLocalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLocalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLocalizarMouseExited(evt);
            }
        });
        JpMenu.add(btnLocalizar);
        btnLocalizar.setBounds(50, 500, 140, 40);

        separarRutas.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarRutas);
        separarRutas.setBounds(0, 380, 200, 20);

        iconQuitPuntoControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/quitPuntoControl.png"))); // NOI18N
        JpMenu.add(iconQuitPuntoControl);
        iconQuitPuntoControl.setBounds(10, 410, 40, 40);

        separarPuntosControl.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarPuntosControl);
        separarPuntosControl.setBounds(0, 470, 200, 20);

        iconTarifaPrioridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarifaPrioridad.png"))); // NOI18N
        JpMenu.add(iconTarifaPrioridad);
        iconTarifaPrioridad.setBounds(10, 590, 40, 40);

        btnTarifaPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaPrioridad.setText("Editar Clientes");
        btnTarifaPrioridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseExited(evt);
            }
        });
        JpMenu.add(btnTarifaPrioridad);
        btnTarifaPrioridad.setBounds(50, 590, 130, 40);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(jSeparator7);
        jSeparator7.setBounds(0, 650, 200, 20);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        JpMenu.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(30, 870, 130, 60);

        separarUsuarios1.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarUsuarios1);
        separarUsuarios1.setBounds(0, 300, 200, 20);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(jSeparator8);
        jSeparator8.setBounds(0, 560, 200, 20);

        ContenedorPrincipal.add(JpMenu, java.awt.BorderLayout.LINE_START);

        JpContenedor.setLayout(new java.awt.BorderLayout());

        JpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        JpTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        JpTitulo.setPreferredSize(new java.awt.Dimension(750, 80));
        JpTitulo.setLayout(null);

        tituloPrincipal.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        tituloPrincipal.setText("Pantalla Principal");
        JpTitulo.add(tituloPrincipal);
        tituloPrincipal.setBounds(770, 10, 260, 50);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpTitulo.add(jSeparator1);
        jSeparator1.setBounds(-10, 0, 1780, 80);

        JpContenedor.add(JpTitulo, java.awt.BorderLayout.PAGE_START);

        JpInfo.setBackground(new java.awt.Color(255, 255, 255));
        JpInfo.setLayout(new java.awt.BorderLayout());
        JpContenedor.add(JpInfo, java.awt.BorderLayout.CENTER);

        ContenedorPrincipal.add(JpContenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContenedorPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecepcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionMouseEntered
        btnRecepcion.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnRecepcionMouseEntered

    private void btnRecepcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionMouseExited
        btnRecepcion.setForeground(Color.white);
    }//GEN-LAST:event_btnRecepcionMouseExited

    private void btnEntregaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregaMouseEntered
        btnEntrega.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnEntregaMouseEntered

    private void btnEntregaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregaMouseExited
        btnEntrega.setForeground(Color.white);
    }//GEN-LAST:event_btnEntregaMouseExited

    private void btnVerNoEntregadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerNoEntregadosMouseEntered
        btnVerNoEntregados.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnVerNoEntregadosMouseEntered

    private void btnVerNoEntregadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerNoEntregadosMouseExited
        btnVerNoEntregados.setForeground(Color.white);
    }//GEN-LAST:event_btnVerNoEntregadosMouseExited

    private void btnLocalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocalizarMouseEntered
        btnLocalizar.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnLocalizarMouseEntered

    private void btnLocalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocalizarMouseExited
        btnLocalizar.setForeground(Color.white);
    }//GEN-LAST:event_btnLocalizarMouseExited

    private void btnRecepcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionMouseClicked
        EnviarPaquetes crear = new EnviarPaquetes();
        tituloPrincipal.setText("Registrando Paquetes...");
        JpInfo.removeAll();
        JpInfo.add(crear, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }//GEN-LAST:event_btnRecepcionMouseClicked

    private void btnEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregaMouseClicked
        EditUser edit = new EditUser();
        tituloPrincipal.setText("Editando Usuario...");
        JpInfo.removeAll();
        JpInfo.add(edit, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }//GEN-LAST:event_btnEntregaMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Conexion.closeConexion();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnVerNoEntregadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerNoEntregadosMouseClicked
        CrearDestino destino = new CrearDestino();
        tituloPrincipal.setText("Creando Destino...");
        JpInfo.removeAll();
        JpInfo.add(destino, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnVerNoEntregadosMouseClicked

    private void btnLocalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocalizarMouseClicked
        CrearRuta ruta = new CrearRuta();
        tituloPrincipal.setText("Creando Ruta...");
        JpInfo.removeAll();
        JpInfo.add(ruta, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnLocalizarMouseClicked

    private void btnTarifaPrioridadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseExited
        btnTarifaPrioridad.setForeground(Color.white);
    }//GEN-LAST:event_btnTarifaPrioridadMouseExited

    private void btnTarifaPrioridadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseEntered
        btnTarifaPrioridad.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnTarifaPrioridadMouseEntered

    private void btnTarifaPrioridadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseClicked
        EditarCliente edit = new EditarCliente();
        tituloPrincipal.setText("Editando Clientes...");
        JpInfo.removeAll();
        JpInfo.add(edit, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnTarifaPrioridadMouseClicked

    public void setText(String string) {
        UserInSesion.setText(string);
    }

    public String getTitulo() {
        return this.tituloPrincipal.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorPrincipal;
    private javax.swing.JPanel JpContenedor;
    private javax.swing.JPanel JpInfo;
    private javax.swing.JPanel JpMenu;
    private javax.swing.JPanel JpTitulo;
    private javax.swing.JLabel UserInSesion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel btnEntrega;
    private javax.swing.JLabel btnLocalizar;
    private javax.swing.JLabel btnRecepcion;
    private javax.swing.JLabel btnTarifaPrioridad;
    private javax.swing.JLabel btnVerNoEntregados;
    private javax.swing.JLabel iconCreateUser;
    private javax.swing.JLabel iconEditUser;
    private javax.swing.JLabel iconNewRuta;
    private javax.swing.JLabel iconQuitPuntoControl;
    private javax.swing.JLabel iconTarifaPrioridad;
    private javax.swing.JLabel iconUserInSesion;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator separarPuntosControl;
    private javax.swing.JSeparator separarRutas;
    private javax.swing.JSeparator separarUserInSesion;
    private javax.swing.JSeparator separarUsuarios;
    private javax.swing.JSeparator separarUsuarios1;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
