/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import Ui.Admin.CrudUsuarios.DesactivarUsuario;
import Ui.Admin.CrudUsuarios.EditUser;
import Ui.Admin.CrudUsuarios.CrearUsuario;
import Ui.Admin.CrudRutas.CrearRuta;
import Ui.Admin.CrudRutas.CrearDestino;
import UI.Info;
import SQL.Conexion;
import UI.Admin.Reportes.ReporteRutas;
import UI.Admin.Tarifas.EditTarifaDestino;
import UI.Login;
import Ui.Admin.Tarifas.Tarifas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Gamcas
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormAdministrador
     */
    ImageIcon icono = new ImageIcon("src/Imagenes/user.png");
    Info info = new Info();
    public static int PANTALLA_ACTIVAR = 1;
    public static int PANTALLA_DESACTIVAR = 2;
    public static int PANTALLA_TARIFA_OPERACION = 1;
    public static int PANTALLA_TARIFA_LIBRA = 2;
    public static int PANTALLA_TARIFA_PRIORIDAD = 3;

    public PrincipalAdmin() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setTitle("Administrador");
        this.setExtendedState(MAXIMIZED_BOTH);
        JpInfo.removeAll();
        JpInfo.add(info, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        ContenedorPrincipal = new javax.swing.JPanel();
        JpMenu = new javax.swing.JPanel();
        iconUserInSesion = new javax.swing.JLabel();
        UserInSesion = new javax.swing.JLabel();
        separarUserInSesion = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        iconCreateUser = new javax.swing.JLabel();
        iconEditUser = new javax.swing.JLabel();
        iconDIsabledUser = new javax.swing.JLabel();
        btnCrearUsuario = new javax.swing.JLabel();
        btnEditarUsuario = new javax.swing.JLabel();
        btnDesUsuario = new javax.swing.JLabel();
        separarUsuarios = new javax.swing.JSeparator();
        iconNewDestino = new javax.swing.JLabel();
        btnNuevoDestino = new javax.swing.JLabel();
        iconNewRuta = new javax.swing.JLabel();
        btnNuevaRuta = new javax.swing.JLabel();
        txtR4 = new javax.swing.JLabel();
        btnReporteRutas = new javax.swing.JLabel();
        separarRutas = new javax.swing.JSeparator();
        btnReporteClientes = new javax.swing.JLabel();
        btnReportesFavoritas = new javax.swing.JLabel();
        iconTarifaOperacion = new javax.swing.JLabel();
        btnTarifaOperacion = new javax.swing.JLabel();
        iconTarifaLibra = new javax.swing.JLabel();
        btnTarifaLibra = new javax.swing.JLabel();
        iconTarifaDestino = new javax.swing.JLabel();
        btnTarifaDestino = new javax.swing.JLabel();
        iconTarifaPrioridad = new javax.swing.JLabel();
        btnTarifaPrioridad = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        iconActivateuser = new javax.swing.JLabel();
        btnActivateuser = new javax.swing.JLabel();
        btnReportesGanancias = new javax.swing.JLabel();
        txtR3 = new javax.swing.JLabel();
        txtR2 = new javax.swing.JLabel();
        txtR1 = new javax.swing.JLabel();
        JpContenedor = new javax.swing.JPanel();
        JpTitulo = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JpInfo = new javax.swing.JPanel();

        jLabel6.setText("fin");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ContenedorPrincipal.setLayout(new java.awt.BorderLayout());

        JpMenu.setBackground(new java.awt.Color(102, 102, 102));
        JpMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        JpMenu.setPreferredSize(new java.awt.Dimension(200, 712));
        JpMenu.setLayout(null);

        iconUserInSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        JpMenu.add(iconUserInSesion);
        iconUserInSesion.setBounds(30, 20, 40, 40);

        UserInSesion.setForeground(new java.awt.Color(255, 255, 255));
        UserInSesion.setText("Nombre Usuario");
        JpMenu.add(UserInSesion);
        UserInSesion.setBounds(70, 20, 110, 40);

        separarUserInSesion.setBackground(new java.awt.Color(0, 0, 0));
        separarUserInSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpMenu.add(separarUserInSesion);
        separarUserInSesion.setBounds(0, 0, 200, 80);
        JpMenu.add(jLabel1);
        jLabel1.setBounds(150, 100, 40, 30);

        iconCreateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearUser.png"))); // NOI18N
        JpMenu.add(iconCreateUser);
        iconCreateUser.setBounds(10, 90, 40, 40);

        iconEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editUser.png"))); // NOI18N
        JpMenu.add(iconEditUser);
        iconEditUser.setBounds(10, 140, 40, 40);

        iconDIsabledUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desusuario.png"))); // NOI18N
        JpMenu.add(iconDIsabledUser);
        iconDIsabledUser.setBounds(10, 180, 40, 40);

        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        JpMenu.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(50, 90, 140, 40);

        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar Usuario");
        btnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseExited(evt);
            }
        });
        JpMenu.add(btnEditarUsuario);
        btnEditarUsuario.setBounds(50, 140, 140, 40);

        btnDesUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnDesUsuario.setText("Desactivar Usuario");
        btnDesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesUsuarioMouseExited(evt);
            }
        });
        JpMenu.add(btnDesUsuario);
        btnDesUsuario.setBounds(50, 180, 140, 40);

        separarUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarUsuarios);
        separarUsuarios.setBounds(0, 270, 200, 20);

        iconNewDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevoDestino.png"))); // NOI18N
        JpMenu.add(iconNewDestino);
        iconNewDestino.setBounds(10, 280, 40, 40);

        btnNuevoDestino.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoDestino.setText("Nuevo Destino");
        btnNuevoDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoDestinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoDestinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoDestinoMouseExited(evt);
            }
        });
        JpMenu.add(btnNuevoDestino);
        btnNuevoDestino.setBounds(50, 280, 140, 40);

        iconNewRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevaRuta.png"))); // NOI18N
        JpMenu.add(iconNewRuta);
        iconNewRuta.setBounds(10, 320, 40, 40);

        btnNuevaRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaRuta.setText("Nueva Ruta");
        btnNuevaRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaRutaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaRutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaRutaMouseExited(evt);
            }
        });
        JpMenu.add(btnNuevaRuta);
        btnNuevaRuta.setBounds(50, 320, 140, 40);

        txtR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        JpMenu.add(txtR4);
        txtR4.setBounds(10, 760, 40, 40);

        btnReporteRutas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteRutas.setText("Reporte de rutas");
        btnReporteRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteRutasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteRutasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteRutasMouseExited(evt);
            }
        });
        JpMenu.add(btnReporteRutas);
        btnReporteRutas.setBounds(50, 600, 140, 40);

        separarRutas.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(separarRutas);
        separarRutas.setBounds(0, 380, 200, 20);

        btnReporteClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteClientes.setText("Reporte de Clientes");
        btnReporteClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteClientesMouseExited(evt);
            }
        });
        JpMenu.add(btnReporteClientes);
        btnReporteClientes.setBounds(50, 710, 140, 40);

        btnReportesFavoritas.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnReportesFavoritas.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesFavoritas.setText("Reporte de rutas favoritas");
        btnReportesFavoritas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesFavoritasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesFavoritasMouseExited(evt);
            }
        });
        JpMenu.add(btnReportesFavoritas);
        btnReportesFavoritas.setBounds(50, 760, 140, 40);

        iconTarifaOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarifaOperacion.png"))); // NOI18N
        JpMenu.add(iconTarifaOperacion);
        iconTarifaOperacion.setBounds(10, 400, 40, 40);

        btnTarifaOperacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaOperacion.setText("Tarifa de Operacion");
        btnTarifaOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaOperacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaOperacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaOperacionMouseExited(evt);
            }
        });
        JpMenu.add(btnTarifaOperacion);
        btnTarifaOperacion.setBounds(50, 400, 130, 40);

        iconTarifaLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarifaLibra.png"))); // NOI18N
        JpMenu.add(iconTarifaLibra);
        iconTarifaLibra.setBounds(10, 440, 40, 40);

        btnTarifaLibra.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaLibra.setText("Tarifa por Libra");
        btnTarifaLibra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaLibraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaLibraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaLibraMouseExited(evt);
            }
        });
        JpMenu.add(btnTarifaLibra);
        btnTarifaLibra.setBounds(50, 440, 130, 40);

        iconTarifaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarifaDestino.png"))); // NOI18N
        JpMenu.add(iconTarifaDestino);
        iconTarifaDestino.setBounds(10, 520, 40, 40);

        btnTarifaDestino.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaDestino.setText("Tarifa de Destino");
        btnTarifaDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaDestinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaDestinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaDestinoMouseExited(evt);
            }
        });
        JpMenu.add(btnTarifaDestino);
        btnTarifaDestino.setBounds(50, 520, 130, 40);

        iconTarifaPrioridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarifaPrioridad.png"))); // NOI18N
        JpMenu.add(iconTarifaPrioridad);
        iconTarifaPrioridad.setBounds(10, 480, 40, 40);

        btnTarifaPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaPrioridad.setText("Tarifa de Prioridad");
        btnTarifaPrioridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaPrioridadMouseExited(evt);
            }
        });
        JpMenu.add(btnTarifaPrioridad);
        btnTarifaPrioridad.setBounds(50, 480, 130, 40);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        JpMenu.add(jSeparator7);
        jSeparator7.setBounds(0, 580, 200, 20);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        JpMenu.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(30, 890, 130, 60);

        iconActivateuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/activarUsuario.png"))); // NOI18N
        JpMenu.add(iconActivateuser);
        iconActivateuser.setBounds(10, 220, 40, 40);

        btnActivateuser.setForeground(new java.awt.Color(255, 255, 255));
        btnActivateuser.setText("Activar Usuario");
        btnActivateuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivateuserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActivateuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActivateuserMouseExited(evt);
            }
        });
        JpMenu.add(btnActivateuser);
        btnActivateuser.setBounds(50, 220, 140, 40);

        btnReportesGanancias.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesGanancias.setText("Reporte de Ganancias");
        btnReportesGanancias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesGananciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesGananciasMouseExited(evt);
            }
        });
        JpMenu.add(btnReportesGanancias);
        btnReportesGanancias.setBounds(50, 660, 140, 40);

        txtR3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        JpMenu.add(txtR3);
        txtR3.setBounds(10, 710, 40, 40);

        txtR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        JpMenu.add(txtR2);
        txtR2.setBounds(10, 660, 40, 40);

        txtR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        JpMenu.add(txtR1);
        txtR1.setBounds(10, 600, 40, 40);

        ContenedorPrincipal.add(JpMenu, java.awt.BorderLayout.LINE_START);

        JpContenedor.setLayout(new java.awt.BorderLayout());

        JpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        JpTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        JpTitulo.setPreferredSize(new java.awt.Dimension(750, 80));
        JpTitulo.setLayout(null);

        tituloPrincipal.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        tituloPrincipal.setText("Pantalla Principal");
        JpTitulo.add(tituloPrincipal);
        tituloPrincipal.setBounds(770, 10, 260, 50);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpTitulo.add(jSeparator1);
        jSeparator1.setBounds(-10, 0, 1780, 80);

        JpContenedor.add(JpTitulo, java.awt.BorderLayout.PAGE_START);

        JpInfo.setBackground(new java.awt.Color(255, 255, 255));
        JpInfo.setLayout(new java.awt.BorderLayout());
        JpContenedor.add(JpInfo, java.awt.BorderLayout.CENTER);

        ContenedorPrincipal.add(JpContenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContenedorPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesUsuarioMouseEntered
        btnDesUsuario.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnDesUsuarioMouseEntered

    private void btnDesUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesUsuarioMouseExited
        btnDesUsuario.setForeground(Color.white);
    }//GEN-LAST:event_btnDesUsuarioMouseExited

    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        btnCrearUsuario.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        btnCrearUsuario.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnEditarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseEntered
        btnEditarUsuario.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnEditarUsuarioMouseEntered

    private void btnEditarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseExited
        btnEditarUsuario.setForeground(Color.white);
    }//GEN-LAST:event_btnEditarUsuarioMouseExited

    private void btnNuevoDestinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoDestinoMouseEntered
        btnNuevoDestino.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnNuevoDestinoMouseEntered

    private void btnNuevoDestinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoDestinoMouseExited
        btnNuevoDestino.setForeground(Color.white);
    }//GEN-LAST:event_btnNuevoDestinoMouseExited

    private void btnNuevaRutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaRutaMouseEntered
        btnNuevaRuta.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnNuevaRutaMouseEntered

    private void btnNuevaRutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaRutaMouseExited
        btnNuevaRuta.setForeground(Color.white);
    }//GEN-LAST:event_btnNuevaRutaMouseExited

    private void btnReporteRutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteRutasMouseEntered
        btnReporteRutas.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnReporteRutasMouseEntered

    private void btnReporteRutasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteRutasMouseExited
        btnReporteRutas.setForeground(Color.white);
    }//GEN-LAST:event_btnReporteRutasMouseExited

    private void btnCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseClicked
        CrearUsuario crear = new CrearUsuario();
        tituloPrincipal.setText("Creando Usuario...");
        JpInfo.removeAll();
        JpInfo.add(crear, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }//GEN-LAST:event_btnCrearUsuarioMouseClicked

    private void btnReporteClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteClientesMouseEntered
        btnReporteClientes.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnReporteClientesMouseEntered

    private void btnReporteClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteClientesMouseExited
        btnReporteClientes.setForeground(Color.white);
    }//GEN-LAST:event_btnReporteClientesMouseExited

    private void btnReportesFavoritasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesFavoritasMouseEntered
        btnReportesFavoritas.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnReportesFavoritasMouseEntered

    private void btnReportesFavoritasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesFavoritasMouseExited
        btnReportesFavoritas.setForeground(Color.white);
    }//GEN-LAST:event_btnReportesFavoritasMouseExited

    private void btnTarifaDestinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaDestinoMouseEntered
        btnTarifaDestino.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnTarifaDestinoMouseEntered

    private void btnTarifaDestinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaDestinoMouseExited
        btnTarifaDestino.setForeground(Color.white);
    }//GEN-LAST:event_btnTarifaDestinoMouseExited

    private void btnTarifaLibraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLibraMouseEntered
        btnTarifaLibra.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnTarifaLibraMouseEntered

    private void btnTarifaLibraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLibraMouseExited
        btnTarifaLibra.setForeground(Color.white);
    }//GEN-LAST:event_btnTarifaLibraMouseExited

    private void btnTarifaOperacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaOperacionMouseEntered
        btnTarifaOperacion.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnTarifaOperacionMouseEntered

    private void btnTarifaOperacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaOperacionMouseExited
        btnTarifaOperacion.setForeground(Color.white);
    }//GEN-LAST:event_btnTarifaOperacionMouseExited

    private void btnEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseClicked
        EditUser edit = new EditUser();
        tituloPrincipal.setText("Editando Usuario...");
        JpInfo.removeAll();
        JpInfo.add(edit, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();

    }//GEN-LAST:event_btnEditarUsuarioMouseClicked

    private void btnTarifaPrioridadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseEntered
        btnTarifaPrioridad.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnTarifaPrioridadMouseEntered

    private void btnTarifaPrioridadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseExited
        btnTarifaPrioridad.setForeground(Color.white);
    }//GEN-LAST:event_btnTarifaPrioridadMouseExited

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnDesUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesUsuarioMouseClicked
        DesactivarUsuario des = new DesactivarUsuario(PANTALLA_DESACTIVAR);
        tituloPrincipal.setText("Desactivando Usuario...");
        JpInfo.removeAll();
        JpInfo.add(des, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnDesUsuarioMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Conexion.closeConexion();
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnActivateuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateuserMouseClicked
        DesactivarUsuario desactivar = new DesactivarUsuario(PANTALLA_ACTIVAR);
        tituloPrincipal.setText("Activando Usuario...");
        JpInfo.removeAll();
        JpInfo.add(desactivar, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnActivateuserMouseClicked

    private void btnActivateuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateuserMouseEntered
        btnActivateuser.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnActivateuserMouseEntered

    private void btnActivateuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateuserMouseExited
        btnActivateuser.setForeground(Color.white);
    }//GEN-LAST:event_btnActivateuserMouseExited

    private void btnNuevoDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoDestinoMouseClicked
        CrearDestino destino = new CrearDestino();
        tituloPrincipal.setText("Creando Destino...");
        JpInfo.removeAll();
        JpInfo.add(destino, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnNuevoDestinoMouseClicked

    private void btnReportesGananciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesGananciasMouseEntered
        btnReportesGanancias.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnReportesGananciasMouseEntered

    private void btnReportesGananciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesGananciasMouseExited
        btnReportesGanancias.setForeground(Color.white);

    }//GEN-LAST:event_btnReportesGananciasMouseExited

    private void btnNuevaRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaRutaMouseClicked
        CrearRuta ruta = new CrearRuta();
        tituloPrincipal.setText("Creando Ruta...");
        JpInfo.removeAll();
        JpInfo.add(ruta, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnNuevaRutaMouseClicked

    private void btnTarifaOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaOperacionMouseClicked
        JpInfo.removeAll();
        JpInfo.add(info, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
        Tarifas tarifa = new Tarifas(this, true, PANTALLA_TARIFA_OPERACION);
        tarifa.setVisible(true);
    }//GEN-LAST:event_btnTarifaOperacionMouseClicked

    private void btnTarifaLibraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLibraMouseClicked
        JpInfo.removeAll();
        JpInfo.add(info, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
        Tarifas tarifa = new Tarifas(this, true, PANTALLA_TARIFA_LIBRA);
        tarifa.setVisible(true);
    }//GEN-LAST:event_btnTarifaLibraMouseClicked

    private void btnTarifaPrioridadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaPrioridadMouseClicked
        JpInfo.removeAll();
        JpInfo.add(info, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
        Tarifas tarifa = new Tarifas(this, true, PANTALLA_TARIFA_PRIORIDAD);
        tarifa.setVisible(true);
    }//GEN-LAST:event_btnTarifaPrioridadMouseClicked

    private void btnTarifaDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaDestinoMouseClicked
        EditTarifaDestino tarifa = new EditTarifaDestino();
        tituloPrincipal.setText("Tarifa de Destino...");
        JpInfo.removeAll();
        JpInfo.add(tarifa, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnTarifaDestinoMouseClicked

    private void btnReporteRutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteRutasMouseClicked
           ReporteRutas reporte = new ReporteRutas();
        tituloPrincipal.setText("Reporte...");
        JpInfo.removeAll();
        JpInfo.add(reporte, BorderLayout.CENTER);
        JpInfo.revalidate();
        JpInfo.repaint();
    }//GEN-LAST:event_btnReporteRutasMouseClicked

    public void setText(String string) {
        UserInSesion.setText(string);
    }

    public String getTitulo() {
        return this.tituloPrincipal.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorPrincipal;
    private javax.swing.JPanel JpContenedor;
    private javax.swing.JPanel JpInfo;
    private javax.swing.JPanel JpMenu;
    private javax.swing.JPanel JpTitulo;
    private javax.swing.JLabel UserInSesion;
    private javax.swing.JLabel btnActivateuser;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel btnCrearUsuario;
    private javax.swing.JLabel btnDesUsuario;
    private javax.swing.JLabel btnEditarUsuario;
    private javax.swing.JLabel btnNuevaRuta;
    private javax.swing.JLabel btnNuevoDestino;
    private javax.swing.JLabel btnReporteClientes;
    private javax.swing.JLabel btnReporteRutas;
    private javax.swing.JLabel btnReportesFavoritas;
    private javax.swing.JLabel btnReportesGanancias;
    private javax.swing.JLabel btnTarifaDestino;
    private javax.swing.JLabel btnTarifaLibra;
    private javax.swing.JLabel btnTarifaOperacion;
    private javax.swing.JLabel btnTarifaPrioridad;
    private javax.swing.JLabel iconActivateuser;
    private javax.swing.JLabel iconCreateUser;
    private javax.swing.JLabel iconDIsabledUser;
    private javax.swing.JLabel iconEditUser;
    private javax.swing.JLabel iconNewDestino;
    private javax.swing.JLabel iconNewRuta;
    private javax.swing.JLabel iconTarifaDestino;
    private javax.swing.JLabel iconTarifaLibra;
    private javax.swing.JLabel iconTarifaOperacion;
    private javax.swing.JLabel iconTarifaPrioridad;
    private javax.swing.JLabel iconUserInSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator separarRutas;
    private javax.swing.JSeparator separarUserInSesion;
    private javax.swing.JSeparator separarUsuarios;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JLabel txtR1;
    private javax.swing.JLabel txtR2;
    private javax.swing.JLabel txtR3;
    private javax.swing.JLabel txtR4;
    // End of variables declaration//GEN-END:variables
}
