/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recepcionista.Paquetes;

import Models.Cliente;
import UI.Admin.CrudUsuarios.*;
import Models.Usuario;
import SQL.ManejoTabla;
import SQL.ObtenerDatos;
import SQL.RegistroCliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class EditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form crearUser
     */
    public static int TODOS_LOS_CLIENTES = 13;
    public static int MOSTRAR_CLIENTE_BUSCADO = 14;

    public EditarCliente() {
        initComponents();
        mostrarClientes();
        btnSave.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtNit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione un Cliente:");
        add(jLabel2);
        jLabel2.setBounds(250, 50, 220, 60);

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 680, 670);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar Cliente:");
        add(jLabel1);
        jLabel1.setBounds(380, 810, 130, 40);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        add(txtBusqueda);
        txtBusqueda.setBounds(510, 810, 190, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        error.setBackground(new java.awt.Color(255, 0, 0));
        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error);
        error.setBounds(280, 610, 260, 60);

        txtNombre.setEnabled(false);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(160, 400, 200, 50);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Edicion Cliente");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 20, 150, 80);

        btnModificar.setText("Modificar Datos");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(340, 250, 160, 70);

        txtNit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNit.setEnabled(false);
        jPanel1.add(txtNit);
        txtNit.setBounds(330, 130, 200, 50);

        jLabel4.setText("Nit");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 100, 30, 40);

        txtTelefono.setEnabled(false);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(310, 540, 200, 50);

        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 500, 60, 40);

        btnSave.setText("Guardar Cambios");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(330, 690, 160, 70);

        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 360, 50, 40);

        txtDireccion.setEnabled(false);
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(490, 400, 200, 50);

        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(560, 360, 60, 40);

        add(jPanel1);
        jPanel1.setBounds(770, 40, 800, 860);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        try {
            ManejoTabla.mostrarTablas(tablaCliente, MOSTRAR_CLIENTE_BUSCADO, String.valueOf(txtBusqueda.getText()));
        } catch (ClassNotFoundException ex) {

        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        int fila = tablaCliente.getSelectedRow();
        txtNombre.setText((String) tablaCliente.getValueAt(fila, 0));
        txtNit.setText(String.valueOf(tablaCliente.getValueAt(fila, 1)));
        txtTelefono.setText(String.valueOf(tablaCliente.getValueAt(fila, 2)));
        txtDireccion.setText((String) tablaCliente.getValueAt(fila, 3));
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (txtNit.getText().isEmpty()) {
            error.setText("Seleccione un usuario");
        } else {
            txtTelefono.setEnabled(true);
            txtDireccion.setEnabled(true);
            txtNombre.setEnabled(true);
            btnSave.setEnabled(true);
            btnModificar.setEnabled(false);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String telefono = txtTelefono.getText();
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        Cliente cliente = new Cliente();
        RegistroCliente registro = new RegistroCliente();

        try {
            if (telefono.isEmpty() || nombre.isEmpty() || direccion.isEmpty()) {
                error.setText("Los campos no pueden estar vacios");
            } else {
                int tele = Integer.parseInt(telefono);
                cliente.setDireccion(direccion);
                cliente.setNombre(nombre);
                cliente.setTelefono(tele);
                cliente.setNit(Integer.parseInt(txtNit.getText()));
                registro.editarCliente(cliente);
                JOptionPane.showMessageDialog(null, "Cliente editado exitosamente");
                btnSave.setEnabled(false);
                btnModificar.setEnabled(true);
                txtBusqueda.setText("");
                txtDireccion.setText("");
                txtNit.setText("");
                txtNombre.setText("");
                error.setText("");
                txtTelefono.setText("");
                txtTelefono.setEnabled(false);
                txtDireccion.setEnabled(false);
                txtNombre.setEnabled(false);
                mostrarClientes();

            }
        } catch (NumberFormatException e) {
            error.setText("El telefono debe de ser un numero");
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void mostrarClientes() {
        try {
            ManejoTabla.mostrarTablas(tablaCliente, TODOS_LOS_CLIENTES, null);
        } catch (ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
