/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recepcionista.Paquetes;

import SQL.ManejoTabla;
import SQL.RegistroPaquete;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class EntregarPaquetes extends javax.swing.JPanel {

    /**
     * Creates new form crearUser
     */
    
    public static int PAQUETES_EN_DESTINO = 16;

    public EntregarPaquetes() {
        initComponents();
        calendario.setDateFormatString("yyyy-MM-dd");
        mostrarPaquetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquete = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPaquete = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        btnEntregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Paquetes por entregar:");
        add(jLabel2);
        jLabel2.setBounds(440, 30, 220, 60);

        tablaPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPaquete);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 110, 930, 670);

        jPanel1.setLayout(null);

        jLabel1.setText("Paquete Seleccionado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 150, 60);
        jPanel1.add(txtPaquete);
        txtPaquete.setBounds(210, 80, 60, 40);
        jPanel1.add(calendario);
        calendario.setBounds(90, 190, 300, 50);

        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntregar);
        btnEntregar.setBounds(170, 380, 130, 70);

        jLabel3.setText("Fecha de Entrega");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 150, 120, 30);

        add(jPanel1);
        jPanel1.setBounds(1110, 110, 460, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPaqueteMouseClicked
        int fila = tablaPaquete.getSelectedRow();
        txtPaquete.setText(tablaPaquete.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablaPaqueteMouseClicked

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        LocalDate entrega = calendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Date date = Date.valueOf(entrega);

        if (txtPaquete.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un paquete");
        } else {
            if ((RegistroPaquete.fechaPaquete(Integer.parseInt(txtPaquete.getText())).compareTo(date))
                    <= (date.compareTo(RegistroPaquete.fechaPaquete(Integer.parseInt(txtPaquete.getText()))))) {

                if (RegistroPaquete.entregarPaquete(date, Integer.parseInt(txtPaquete.getText()))) {
                    JOptionPane.showMessageDialog(null, "El paquete ha sido entregado con exito");
                    txtPaquete.setText("");
                    mostrarPaquetes();
                } else {
                    JOptionPane.showMessageDialog(null, "ha ocurrido un error");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La fecha de recepcion debe de ser mayo a la de entrega");
            }
        }

    }//GEN-LAST:event_btnEntregarActionPerformed

    private void mostrarPaquetes() {
        try {
            ManejoTabla.mostrarTablas(tablaPaquete, PAQUETES_EN_DESTINO, null);
        } catch (ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaquete;
    private javax.swing.JLabel txtPaquete;
    // End of variables declaration//GEN-END:variables
}
