/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Recepcionista.Paquetes;

import SQL.ManejoTabla;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class LocalizarPaquete extends javax.swing.JPanel {

    /**
     * Creates new form crearUser
     */
    public static int PAQUETES_EN_DESTINO = 17;

    public LocalizarPaquete() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquete = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Paquetes en Ruta");
        add(jLabel2);
        jLabel2.setBounds(750, 120, 220, 60);

        tablaPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPaquete);

        add(jScrollPane1);
        jScrollPane1.setBounds(380, 200, 930, 670);

        jLabel1.setText("Buscar Cliente (Nit):");
        add(jLabel1);
        jLabel1.setBounds(550, 30, 130, 50);
        add(txtBusqueda);
        txtBusqueda.setBounds(680, 30, 200, 50);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(940, 30, 130, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPaqueteMouseClicked

    }//GEN-LAST:event_tablaPaqueteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtBusqueda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un nit");
        } else {
            mostrarPaquetes();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarPaquetes() {
        try {
            ManejoTabla.mostrarTablas(tablaPaquete, PAQUETES_EN_DESTINO, txtBusqueda.getText());
        } catch (ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaquete;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
