/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UiAdmin.CrudRutas;

import Models.Destino;
import SQL.ManejoTabla;
import SQL.RegistroDestino;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class CrearDestino extends javax.swing.JPanel {

    public static int TODOS_LOS_DESTINO = 7;
    public static int BUSCAR_DESTINO = 8;

    public CrearDestino() {
        initComponents();
        mostrarDestinos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Listado de Destinos:");
        add(jLabel2);
        jLabel2.setBounds(330, 40, 220, 60);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 950, 710);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Budcar Destino:");
        add(jLabel1);
        jLabel1.setBounds(280, 830, 130, 40);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        add(txtBusqueda);
        txtBusqueda.setBounds(400, 830, 210, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        btnSave.setText("Agregar Destino");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(230, 480, 160, 70);

        txtDestino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDestino);
        txtDestino.setBounds(60, 240, 200, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Agregar Nuevo Destino");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 40, 210, 70);

        jLabel5.setText("Nombre Destino:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 200, 130, 40);

        jLabel6.setText("Cuota de Destino:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 200, 130, 40);

        txtCuota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCuota);
        txtCuota.setBounds(320, 240, 200, 50);

        lblError.setBackground(new java.awt.Color(255, 0, 0));
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblError);
        lblError.setBounds(230, 350, 220, 80);

        add(jPanel1);
        jPanel1.setBounds(1050, 90, 590, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        try {
            ManejoTabla.mostrarTablas(tablaUsuarios, BUSCAR_DESTINO, txtBusqueda.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearDestino.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String nombre = txtDestino.getText();
        String cuota = txtCuota.getText();
        Destino destino = new Destino();
        RegistroDestino registro = new RegistroDestino();

        try {
            if (nombre.isEmpty() || cuota.isEmpty()) {

                lblError.setText("Todos los campos son obligatotios");

            } else {
                lblError.setText("");

                if (registro.existeDestino(nombre) == 0) {

                    destino.setCuota(Double.parseDouble(cuota));
                    destino.setNombreDestino(nombre);

                    if (registro.crearDestino(destino)) {

                        JOptionPane.showMessageDialog(null, "Destino Creado exitosamente");
                        mostrarDestinos();
                        limpiar();
                    }

                } else {
                    lblError.setText("El destino ya existe");
                }
            }

        } catch (NumberFormatException e) {
            lblError.setText("La cuota debe ser un numero");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void limpiar() {
        txtBusqueda.setText("");
        txtDestino.setText("");
        txtCuota.setText("");
    }

    private void mostrarDestinos() {
        try {
            ManejoTabla.mostrarTablas(tablaUsuarios, TODOS_LOS_DESTINO, null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearDestino.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtDestino;
    // End of variables declaration//GEN-END:variables
}
