/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.CrudRutas;

import UI.Admin.CrudUsuarios.*;
import Models.Usuario;
import SQL.ManejoTabla;
import SQL.ObtenerDatos;
import SQL.RegistrarUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamcas
 */
public class DesactivarRuta extends javax.swing.JPanel {

    public static int TODOS_LOS_USUARIOS_ACTIVOS = 3;
    public static int TODOS_LOS_USUARIOS_INACTIVOS = 4;
    public static int BUSCAR_USUARIO_ACTIVO = 5;
    public static int BUSCAR_USUARIO_INACTIVO = 6;

    public DesactivarRuta(int act_des) {
        initComponents();

        if (act_des == 1) {
            mostrarUsuarios(TODOS_LOS_USUARIOS_INACTIVOS);
            btnSave.setText("Activar Usuario");
        } else {
            mostrarUsuarios(TODOS_LOS_USUARIOS_ACTIVOS);
            btnSave.setText("Desactivar Usuario");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRuta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione una Ruta:");
        add(jLabel2);
        jLabel2.setBounds(360, 40, 220, 60);

        tablaRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRutaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRuta);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 950, 680);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Buscar ruta;");
        add(jLabel1);
        jLabel1.setBounds(650, 830, 130, 40);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        add(txtBusqueda);
        txtBusqueda.setBounds(780, 830, 190, 40);

        jLabel4.setText("Usuario:");
        add(jLabel4);
        jLabel4.setBounds(1320, 190, 70, 40);

        btnSave.setText("Botom");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(1270, 400, 160, 70);

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setEnabled(false);
        add(txtUser);
        txtUser.setBounds(1250, 250, 200, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped

        if (btnSave.getText().equals("Desactivar Usuario")) {
            try {
                ManejoTabla.mostrarTablas(tablaRuta, BUSCAR_USUARIO_ACTIVO, txtBusqueda.getText());
            } catch (ClassNotFoundException ex) {

            }
        } else {
            try {
                ManejoTabla.mostrarTablas(tablaRuta, BUSCAR_USUARIO_INACTIVO, txtBusqueda.getText());
            } catch (ClassNotFoundException ex) {

            }
        }

    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void tablaRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRutaMouseClicked
        int fila = tablaRuta.getSelectedRow();
        txtUser.setText((String) tablaRuta.getValueAt(fila, 0));

    }//GEN-LAST:event_tablaRutaMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        Usuario user = new Usuario();
        RegistrarUsuario registro = new RegistrarUsuario();
        String usuario = txtUser.getText();

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un usuario");
        } else {
            if (btnSave.getText().equals("Desactivar Usuario")) {

                if (ObtenerDatos.obtenerPuntosUsuario(usuario) == 0) {
                    user.setEstado("INACTIVO");
                    user.setUsuario(usuario);
                    registro.desactivarUsuario(user);
                    mostrarUsuarios(TODOS_LOS_USUARIOS_ACTIVOS);
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Se ha desactivado el usuario");
                } else {
                    JOptionPane.showMessageDialog(null, "Usuarios en puntos de control"
                            + "\nno pueden ser desactivados");
                }

            } else {
                user.setEstado("ACTIVO");
                user.setUsuario(usuario);
                registro.desactivarUsuario(user);
                mostrarUsuarios(TODOS_LOS_USUARIOS_INACTIVOS);
                limpiar();
                JOptionPane.showMessageDialog(null, "Se ha activado el usuario");
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void limpiar() {
        txtBusqueda.setText("");
        txtUser.setText("");

    }

    private void mostrarUsuarios(int mostrar) {
        try {
            ManejoTabla.mostrarTablas(tablaRuta, mostrar, null);
        } catch (ClassNotFoundException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRuta;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
