/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Operador;


import UI.Info;
import SQL.Conexion;
import SQL.ManejoTabla;
import UI.Login;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author Gamcas
 */
public class PrincipalOperado1 extends javax.swing.JFrame {

    /**
     * Creates new form FormAdministrador
     */
    ImageIcon icono = new ImageIcon("src/Imagenes/user.png");
    Info info = new Info();
    public static int MOSTRAR_PUNTOS = 15;
    private String nombre;

    public PrincipalOperado1() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setTitle("Operador");
        this.setSize(1200, 900);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        ContenedorPrincipal = new javax.swing.JPanel();
        JpMenu = new javax.swing.JPanel();
        iconUserInSesion = new javax.swing.JLabel();
        UserInSesion = new javax.swing.JLabel();
        separarUserInSesion = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        JpContenedor = new javax.swing.JPanel();
        JpTitulo = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JpInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOperador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        jLabel6.setText("fin");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ContenedorPrincipal.setLayout(new java.awt.BorderLayout());

        JpMenu.setBackground(new java.awt.Color(102, 102, 102));
        JpMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        JpMenu.setPreferredSize(new java.awt.Dimension(200, 712));
        JpMenu.setLayout(null);

        iconUserInSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        JpMenu.add(iconUserInSesion);
        iconUserInSesion.setBounds(30, 20, 40, 40);

        UserInSesion.setForeground(new java.awt.Color(255, 255, 255));
        UserInSesion.setText("Nombre Usuario");
        JpMenu.add(UserInSesion);
        UserInSesion.setBounds(70, 20, 110, 40);

        separarUserInSesion.setBackground(new java.awt.Color(0, 0, 0));
        separarUserInSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpMenu.add(separarUserInSesion);
        separarUserInSesion.setBounds(0, 0, 200, 80);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        JpMenu.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(30, 700, 130, 60);

        ContenedorPrincipal.add(JpMenu, java.awt.BorderLayout.LINE_START);

        JpContenedor.setLayout(new java.awt.BorderLayout());

        JpTitulo.setBackground(new java.awt.Color(255, 255, 255));
        JpTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        JpTitulo.setPreferredSize(new java.awt.Dimension(750, 80));
        JpTitulo.setLayout(null);

        tituloPrincipal.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        tituloPrincipal.setText("Pantalla Principal");
        JpTitulo.add(tituloPrincipal);
        tituloPrincipal.setBounds(370, 10, 220, 50);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpTitulo.add(jSeparator1);
        jSeparator1.setBounds(-10, 0, 1780, 80);

        JpContenedor.add(JpTitulo, java.awt.BorderLayout.PAGE_START);

        JpInfo.setBackground(new java.awt.Color(255, 255, 255));
        JpInfo.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tablaOperador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaOperador);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(123, 70, 740, 270);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione un punto de control:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 20, 230, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Costo del paquete");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 500, 230, 40);

        jLabel3.setText("Ruta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 390, 120, 40);

        jButton1.setText("Mover Paquete");
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 670, 140, 80);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 430, 170, 50);

        jLabel4.setText("No. punto de control");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 390, 120, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(400, 430, 170, 50);

        jLabel5.setText("Id Paquete ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 390, 120, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(620, 430, 170, 50);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 580, 170, 50);

        jLabel7.setText("Tarifa de Operacion");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 540, 120, 40);

        jLabel8.setText("Horas ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 540, 120, 40);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(400, 580, 170, 50);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Punto de control Seleccionado");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 350, 230, 40);

        jLabel10.setText("Costo");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(620, 540, 120, 40);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(620, 580, 170, 50);

        JpInfo.add(jPanel1, java.awt.BorderLayout.CENTER);

        JpContenedor.add(JpInfo, java.awt.BorderLayout.CENTER);

        ContenedorPrincipal.add(JpContenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContenedorPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Conexion.closeConexion();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nombre = UserInSesion.getText();
        mostarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void mostarTabla() {
        try {
            ManejoTabla.mostrarTablas(tablaOperador, MOSTRAR_PUNTOS, nombre);
        } catch (ClassNotFoundException ex) {
        }
    }

    public void setText(String string) {
        UserInSesion.setText(string);
    }

    public String getTitulo() {
        return this.tituloPrincipal.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalOperado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalOperado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalOperado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalOperado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalOperado1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorPrincipal;
    private javax.swing.JPanel JpContenedor;
    private javax.swing.JPanel JpInfo;
    private javax.swing.JPanel JpMenu;
    private javax.swing.JPanel JpTitulo;
    private javax.swing.JLabel UserInSesion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel iconUserInSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JSeparator separarUserInSesion;
    private javax.swing.JTable tablaOperador;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
