/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UiAdmin.Tarifas;

import SQL.ObtenerDatos;
import java.sql.Date;
import java.time.LocalDate;

/**
 *
 * @author Gamcas
 */
public class TarifaOperacion extends javax.swing.JDialog {

    private LocalDate hoy = LocalDate.now();
    Date date = Date.valueOf(hoy);

    /**
     * Creates new form TarifaOperacion
     */
    public TarifaOperacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(700, 400);
        this.setTitle("Tarifa Operacion");
        this.setLocationRelativeTo(null);
        mostrarTarifa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTarifaActual = new javax.swing.JTextField();
        txtNueva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Asignar Tarifa de Operacion Global");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 330, 70);

        jLabel2.setText("Tarifa Acutal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 90, 30);

        txtTarifaActual.setEnabled(false);
        getContentPane().add(txtTarifaActual);
        txtTarifaActual.setBounds(80, 130, 190, 40);
        getContentPane().add(txtNueva);
        txtNueva.setBounds(400, 130, 190, 40);

        jLabel3.setText("Nueva Tarifa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 100, 90, 30);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 250, 150, 70);

        error.setBackground(new java.awt.Color(255, 0, 51));
        error.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(error);
        error.setBounds(230, 190, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNueva.getText().isEmpty()) {
            error.setText("Ingrese una tarifa");
        }else{
            if (txtNueva.getText().equals("0")) {
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarTarifa() {
        if (!(ObtenerDatos.obtonerTarifaOperacion() == null)) {
            txtTarifaActual.setText(ObtenerDatos.obtonerTarifaOperacion());
        } else {
            this.txtTarifaActual.setText("No hay una tarifa aun");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifaOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TarifaOperacion dialog = new TarifaOperacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNueva;
    private javax.swing.JTextField txtTarifaActual;
    // End of variables declaration//GEN-END:variables
}
