/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UiAdmin;

/**
 *
 * @author Gamcas
 */
public class crearUser extends javax.swing.JPanel {

    /**
     * Creates new form crearUser
     */
    public crearUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        txtContra2 = new javax.swing.JPasswordField();
        txtContra = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(246, 246, 246));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 60, 260, 50);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(60, 110, 320, 50);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 60, 260, 50);
        jPanel1.add(txtApellido);
        txtApellido.setBounds(450, 110, 320, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("Tipo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 240, 160, 50);
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(60, 290, 320, 50);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setText("Contrasena:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 420, 260, 50);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setText("Nombre de Usuario:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 240, 260, 50);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Recepcionista" }));
        jPanel1.add(cmbTipo);
        cmbTipo.setBounds(460, 290, 190, 50);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setText("Confirmar Contrasena:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 420, 260, 50);

        btnConfirmar.setBackground(new java.awt.Color(153, 153, 153));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(330, 650, 180, 70);

        error.setBackground(new java.awt.Color(255, 51, 51));
        error.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(error);
        error.setBounds(320, 560, 230, 60);
        jPanel1.add(txtContra2);
        txtContra2.setBounds(450, 470, 320, 50);
        jPanel1.add(txtContra);
        txtContra.setBounds(60, 470, 320, 50);

        add(jPanel1);
        jPanel1.setBounds(460, 20, 840, 890);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String usuario = txtUsuario.getText();
        String contra = new String(txtContra.getPassword());
        String contra2 = new String(txtContra2.getPassword());

        if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || contra.isEmpty() || contra2.isEmpty()) {
            error.setText("Todos los campos son obligatorios");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtContra2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
